In [1]:
# references: https://github.com/rougier/numpy-100

#### 1. Import the numpy package under the name

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [3]:
print(np.__version__)
np.show_config

1.18.1


<function numpy.__config__.show()>

#### 3. Create a null vector of size 10

In [5]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array 

In [9]:
Z = np.zeros((5, 10))
print("%d bytes" % (Z.size * Z.itemsize))

400 bytes


#### 5. How to get the documentation of the numpy add function from the command line?

In [10]:
%run 'python -c "import numpy; numpy.info(numpy.add)"'

ERROR:root:File `"'python.py"` not found.


#### 6. Create a null vector of size 10 but the fifth value which is 1 

In [21]:
Z = np.zeros(10)

In [22]:
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [23]:
Z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49#### 

In [27]:
Z = np.arange(10, 49)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#### 8. Reverse a vector (first element becomes last)

In [29]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8

In [30]:
Z = np.arange(9).reshape(3, 3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [31]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix 

In [32]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values

In [36]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.24005142 0.69984239 0.87419928]
  [0.28102735 0.32129407 0.00713855]
  [0.44028273 0.41956922 0.71526827]]

 [[0.16756401 0.21831256 0.2449283 ]
  [0.45733643 0.05723837 0.13517924]
  [0.37881155 0.78120672 0.5118414 ]]

 [[0.87642991 0.78433199 0.05834727]
  [0.72341783 0.98477378 0.67748616]
  [0.05373256 0.74159487 0.27781624]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [37]:
Z = np.random.random((10, 10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.0031345795632308215 0.9997232980201748
