In [1]:
# references: https://github.com/rougier/numpy-100

#### 1. Import the numpy package under the name

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [3]:
print(np.__version__)
np.show_config

1.18.1


<function numpy.__config__.show()>

#### 3. Create a null vector of size 10

In [4]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array 

In [5]:
Z = np.zeros((5, 10))
print("%d bytes" % (Z.size * Z.itemsize))

400 bytes


#### 5. How to get the documentation of the numpy add function from the command line?

In [6]:
%run 'python -c "import numpy; numpy.info(numpy.add)"'

ERROR:root:File `"'python.py"` not found.


#### 6. Create a null vector of size 10 but the fifth value which is 1 

In [7]:
Z = np.zeros(10)

In [8]:
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [9]:
Z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49#### 

In [10]:
Z = np.arange(10, 49)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#### 8. Reverse a vector (first element becomes last)

In [11]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8

In [12]:
Z = np.arange(9).reshape(3, 3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [13]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix 

In [14]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values

In [15]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.21047028 0.36845134 0.42227535]
  [0.47947296 0.59437238 0.59622142]
  [0.68808977 0.28075513 0.32728022]]

 [[0.7572033  0.27069034 0.38580843]
  [0.77503557 0.56130396 0.42386242]
  [0.98396908 0.30184952 0.97528884]]

 [[0.92976509 0.69595204 0.1035946 ]
  [0.63835045 0.02195183 0.15041249]
  [0.54046998 0.1576636  0.6372788 ]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [16]:
Z = np.random.random((10, 10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.00039280848795097967 0.995299053533479


#### 14. Create a random vector of size 30 and find the mean value 

In [17]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.5146461058410032


#### 15. Create a 2d array with 1 on the border and 0 inside

In [18]:
Z = np.ones((10, 10))

In [19]:
Z[1:-1, 1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [20]:
Z = np.ones((5,5))

In [21]:
Z = np.pad(Z, pad_width=1, mode='constant', constant_values = 0)

In [22]:
Z

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? 

In [23]:
0 * np.nan

nan

In [24]:
np.nan == np.nan

False

In [25]:
np.inf > np.nan

False

In [26]:
np.nan - np.nan

nan

In [27]:
np.nan in set([np.nan])

True

In [28]:
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [29]:
Z = np.diag(1+np.arange(4), k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern 

In [30]:
Z = np.zeros((8,8), dtype=int)
Z[1::2, ::2] = 1
Z[::2, 1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [31]:
print(np.unravel_index(99, (6, 7, 8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function 

In [32]:
Z = np.tile(np.array([[0,1], [1,0]]), (4,4))

In [33]:
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix

In [34]:
Z = np.random.random((5,5))

In [35]:
Z = (Z - np.mean(Z))/(np.std(Z))

In [36]:
print(Z)

[[-0.19868503  0.59069544 -1.00778039  1.00599521  0.54358202]
 [ 0.31857008 -1.74599174  0.49176831  0.82199259 -0.67146333]
 [ 0.96490492 -0.40171305 -1.35920877  1.55254078  0.92955971]
 [-1.29780216  0.44578567  1.68576486 -0.83689755  0.09586123]
 [ 1.09427715 -1.24823936  0.21285247 -0.17229626 -1.81407279]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) 

In [37]:
color = np.dtype(
                [
                    ("r", np.ubyte),
                    ("g", np.ubyte),
                    ("b", np.ubyte),
                    ("a", np.ubyte)
                ]
                )

In [38]:
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [39]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [40]:
Z= np.ones((5,3))@np.ones((3,2))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [41]:
Z = np.arange(11)
Z[(3<Z)&(Z<8)] *= -1

In [42]:
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? 

In [43]:
print(sum(range(5), -1))
# 5 + 4

9


In [44]:
print(sum(range(5), 2))
# 5 + 7

12


#### 27. Consider an integer vector Z, which of these expressions are legal?

In [45]:
Z = np.random.random((3,3))

In [46]:
Z

array([[0.24233219, 0.12371722, 0.6226189 ],
       [0.70703875, 0.22750208, 0.28532105],
       [0.20084566, 0.08513255, 0.9386236 ]])

In [47]:
Z_to_Z = Z**Z

In [48]:
Z_to_Z

array([[0.70928862, 0.77217899, 0.74452436],
       [0.78261924, 0.71402404, 0.6991901 ],
       [0.72440752, 0.81080481, 0.94227972]])

#### 28. What are the result of the following expressions?

In [49]:
np.array(0) / np.array(0)

C:\Users\Norto\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [50]:
np.array(0) // np.array(0)

C:\Users\Norto\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [51]:
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

#### 29. How to round away from zero a float array ?

In [52]:
Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

[ 4.  3. -7.  7.  2.  9.  5. -6.  4. -1.]


In [53]:
# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

[ 4.  3. -7.  7.  2.  9.  5. -6.  4. -1.]


#### 30. How to find common values between two arrays?

In [54]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[0 5 6 7 9]


#### 31. How to ignore all numpy warnings (not recommended)?

In [55]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

In [56]:
# Back to sanity
_ = np.seterr(**defaults)

In [57]:
# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0

#### 32. Is the following expressions true?

In [58]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\Norto\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? 

In [59]:
yesterday = np.datetime64('today') - np.timedelta64(1)

In [60]:
today     = np.datetime64('today')

In [61]:
tomorrow  = np.datetime64('today') + np.timedelta64(1)

In [62]:
yesterday

numpy.datetime64('2021-05-18')

In [63]:
today

numpy.datetime64('2021-05-19')

In [64]:
tomorrow

numpy.datetime64('2021-05-20')

#### 34. How to get all the dates corresponding to the month of July 2016?

In [65]:
z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')

In [66]:
print(z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? 

In [67]:
A = np.ones(3)*1
B = np.ones(3)*2

In [68]:
np.add(A,B,out=B)

array([3., 3., 3.])

In [69]:
np.divide(A,2,out=A)

array([0.5, 0.5, 0.5])

In [70]:
np.negative(A,out=A)

array([-0.5, -0.5, -0.5])

In [71]:
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods

In [72]:
Z = np.random.uniform(0,10,10)

In [73]:
print(Z - Z%1)

[5. 4. 1. 7. 8. 8. 9. 2. 7. 1.]


In [74]:
print(Z // 1)

[5. 4. 1. 7. 8. 8. 9. 2. 7. 1.]


In [75]:
print(np.floor(Z))

[5. 4. 1. 7. 8. 8. 9. 2. 7. 1.]


In [76]:
print(Z.astype(int))

[5 4 1 7 8 8 9 2 7 1]


In [77]:
print(np.trunc(Z))

[5. 4. 1. 7. 8. 8. 9. 2. 7. 1.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 

In [78]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [79]:
# without broadcasting
Z = np.tile(np.arange(0, 5), (5,1))
print(Z)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array

In [80]:
def generate():
    for x in range(10):
        yield x

In [81]:
Z = np.fromiter(generate(),dtype=float,count=-1)

In [82]:
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [83]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it

In [84]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.17704865 0.22981395 0.27701805 0.28465887 0.39294148 0.47196734
 0.56238672 0.82569433 0.89858736 0.98517254]


#### 41. How to sum a small array faster than np.sum? 

In [90]:
Z = np.arange(10)
np.add.reduce(Z)

45

#### 42. Consider two random array A and B, check if they are equal

In [92]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


#### 43. Make an array immutable (read-only) 

In [93]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates 

In [94]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.99224137 0.68679711 1.02436395 0.10396167 0.98097833 0.66345711
 1.38408927 0.78117955 0.09380253 0.63842073]
[0.53835666 0.50683203 0.39847175 0.70257574 0.18777873 1.02531321
 0.77023133 1.43771557 0.0293575  0.20202592]


#### 45. Create random vector of size 10 and replace the maximum value by 0

In [95]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.56841155 0.25161705 0.2136624  0.88241694 0.         0.48983397
 0.61038633 0.37659162 0.84800197 0.65393349]


#### 46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area

In [3]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [4]:
# Author: Evgeni Burovski
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type

In [3]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array?

In [3]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector?

In [4]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

92


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b)

In [2]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\Norto\anaconda3\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances

In [3]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.40088216 0.23936327 0.58967317 0.36357976 0.15484873
  0.58373353 0.61021769 0.32631533 0.59248781]
 [0.40088216 0.         0.41374993 0.79829939 0.20953003 0.25971918
  0.36755294 0.5165959  0.72090659 0.66683962]
 [0.23936327 0.41374993 0.         0.400471   0.49091257 0.20132061
  0.41956564 0.39139743 0.40115447 0.3553187 ]
 [0.58967317 0.79829939 0.400471   0.         0.89121185 0.60070344
  0.6505054  0.49584086 0.50606261 0.24513223]
 [0.36357976 0.20953003 0.49091257 0.89121185 0.         0.29091018
  0.57138328 0.70137552 0.68305964 0.80812148]
 [0.15484873 0.25971918 0.20132061 0.60070344 0.29091018 0.
  0.44052455 0.49703899 0.46244843 0.53921216]
 [0.58373353 0.36755294 0.41956564 0.6505054  0.57138328 0.44052455
  0.         0.19423168 0.82039006 0.43497197]
 [0.61021769 0.5165959  0.39139743 0.49584086 0.70137552 0.49703899
  0.19423168 0.         0.77497235 0.25931395]
 [0.32631533 0.72090659 0.40115447 0.50606261 0.68305964 0.46244843
  0.82039006 0.77497

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [2]:
# Thanks Vikas (https://stackoverflow.com/a/10622758/5989906)
# & unutbu (https://stackoverflow.com/a/4396247/5989906)
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[77 95 83 26  5 85 45 74 22 76]


#### 54. How to read the following file?

1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11

In [3]:
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays?#### 

In [4]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array

In [5]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? 

In [2]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix

In [3]:
# Author: Warren Weckesser

X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[ 0.37986249  0.21808928 -0.40418681 -0.06651347  0.05623639 -0.46142433
   0.13717544  0.43841916 -0.29860413  0.00094598]
 [ 0.29158131  0.3371255  -0.22122193 -0.3441778   0.11991449  0.19024203
  -0.58965887 -0.08254793  0.08306367  0.21567953]
 [ 0.32313715  0.03503826  0.28557649  0.1891081  -0.3131286  -0.40931762
  -0.22169359  0.33403207  0.10229068 -0.32504296]
 [ 0.14723899  0.14733475  0.07317897 -0.00770973  0.11261775  0.34849738
   0.16703666 -0.12954447 -0.50867972 -0.34997057]
 [-0.08220363  0.02510567 -0.30528513  0.05560356 -0.14226538  0.19138428
   0.10490126  0.27840447 -0.34178325  0.21613814]]


#### 59. How to sort an array by the nth column?

In [4]:
# Author: Steve Tjoa

Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[1 5 3]
 [6 7 0]
 [6 0 4]]
[[6 0 4]
 [1 5 3]
 [6 7 0]]


#### 60. How to tell if a given 2D array has null columns?

In [7]:
# Author: Warren Weckesser

Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

True


#### 61. Find the nearest value from a given value in an array 

In [8]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5225139151418967


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? 

In [2]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute 

In [3]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [3]:
# Author: Brett Olsen

Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution
# Author: Bartosz Telenczuk
np.add.at(Z, I, 1)
print(Z)

[5. 2. 3. 4. 5. 2. 4. 1. 2. 2.]
[9. 3. 5. 7. 9. 3. 7. 1. 3. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?

In [4]:
# Author: Alan G Isaac

X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors

In [5]:
# Author: Fisher Wang

w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

# Faster version
# Author: Mark Setchell
# https://stackoverflow.com/a/59671950/2836621

w, h = 256, 256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8)

# View each pixel as a single 24-bit integer, rather than three 8-bit bytes
I24 = np.dot(I.astype(np.uint32),[1,256,65536])

# Count unique colours
n = len(np.unique(I24))
print(n)

64
64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once?

In [6]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[58 50 46 58]
 [71 54 60 63]
 [44 46 61 64]]
[[58 50 46 58]
 [71 54 60 63]
 [44 46 61 64]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices? 

In [7]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.43189596 0.43994056 0.49008441 0.24817664 0.51364667 0.57317834
 0.42748017 0.40808507 0.52452588 0.4833356 ]
0    0.431896
1    0.439941
2    0.490084
3    0.248177
4    0.513647
5    0.573178
6    0.427480
7    0.408085
8    0.524526
9    0.483336
dtype: float64


#### 69. How to get the diagonal of a dot product? 

In [8]:
# Author: Mathieu Blondel

A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([1.11067382, 1.14547801, 1.18500186, 2.20587893, 1.10950829])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [9]:
# Author: Warren Weckesser

Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?

In [2]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array?

In [3]:
# Author: Eelco Hoogendoorn

A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles

In [2]:
# Author: Nicolas P. Rougier

faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 48) ( 0, 94) ( 3, 29) ( 3, 44) ( 3, 68) ( 3, 92) ( 8, 23) ( 8, 40)
 (13, 40) (13, 55) (13, 79) (13, 89) (18, 88) (18, 99) (23, 40) (29, 44)
 (34, 51) (40, 55) (42, 50) (42, 77) (48, 94) (50, 77) (51, 51) (58, 62)
 (58, 94) (62, 94) (68, 92) (79, 89) (88, 99)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? 

In [3]:
# Author: Jaime Fernández del Río

C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


In [5]:
from platform import python_version

print(python_version())

3.7.6


#### 75. How to compute averages using a sliding window over an array?

In [6]:
# Author: Jaime Fernández del Río

def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) 

In [2]:
# Author: Joe Kington / Erik Rigtorp

from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]
