In [1]:
# references: https://github.com/rougier/numpy-100

#### 1. Import the numpy package under the name

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [3]:
print(np.__version__)
np.show_config

1.18.1


<function numpy.__config__.show()>

#### 3. Create a null vector of size 10

In [5]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array 

In [9]:
Z = np.zeros((5, 10))
print("%d bytes" % (Z.size * Z.itemsize))

400 bytes


#### 5. How to get the documentation of the numpy add function from the command line?

In [10]:
%run 'python -c "import numpy; numpy.info(numpy.add)"'

ERROR:root:File `"'python.py"` not found.


#### 6. Create a null vector of size 10 but the fifth value which is 1 

In [21]:
Z = np.zeros(10)

In [22]:
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [23]:
Z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49#### 

In [27]:
Z = np.arange(10, 49)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
