In [4]:
# references: https://github.com/rougier/numpy-100

#### 1. Import the numpy package under the name

In [5]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [6]:
print(np.__version__)
np.show_config

1.18.1


<function numpy.__config__.show()>

#### 3. Create a null vector of size 10

In [7]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array 

In [8]:
Z = np.zeros((5, 10))
print("%d bytes" % (Z.size * Z.itemsize))

400 bytes


#### 5. How to get the documentation of the numpy add function from the command line?

In [9]:
%run 'python -c "import numpy; numpy.info(numpy.add)"'

ERROR:root:File `"'python.py"` not found.


#### 6. Create a null vector of size 10 but the fifth value which is 1 

In [10]:
Z = np.zeros(10)

In [11]:
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [12]:
Z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49#### 

In [13]:
Z = np.arange(10, 49)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#### 8. Reverse a vector (first element becomes last)

In [14]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8

In [15]:
Z = np.arange(9).reshape(3, 3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [16]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix 

In [17]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values

In [18]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.27798584 0.0664606  0.09883229]
  [0.45975181 0.39427141 0.82077103]
  [0.22008144 0.01404522 0.70166627]]

 [[0.21616577 0.1713059  0.52259647]
  [0.49847164 0.66776093 0.34295983]
  [0.75722889 0.45062936 0.51411669]]

 [[0.66278537 0.93344993 0.87483806]
  [0.95650635 0.38400329 0.97848507]
  [0.43606129 0.93487702 0.12874294]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [19]:
Z = np.random.random((10, 10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.02010194909261509 0.9996201819510006


#### 14. Create a random vector of size 30 and find the mean value 

In [20]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.43476272225676543


#### 15. Create a 2d array with 1 on the border and 0 inside

In [21]:
Z = np.ones((10, 10))

In [22]:
Z[1:-1, 1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [23]:
Z = np.ones((5,5))

In [24]:
Z = np.pad(Z, pad_width=1, mode='constant', constant_values = 0)

In [25]:
Z

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? 

In [26]:
0 * np.nan

nan

In [27]:
np.nan == np.nan

False

In [28]:
np.inf > np.nan

False

In [29]:
np.nan - np.nan

nan

In [30]:
np.nan in set([np.nan])

True

In [31]:
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [32]:
Z = np.diag(1+np.arange(4), k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern 

In [33]:
Z = np.zeros((8,8), dtype=int)
Z[1::2, ::2] = 1
Z[::2, 1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [34]:
print(np.unravel_index(99, (6, 7, 8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function 

In [35]:
Z = np.tile(np.array([[0,1], [1,0]]), (4,4))

In [36]:
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix

In [37]:
Z = np.random.random((5,5))

In [38]:
Z = (Z - np.mean(Z))/(np.std(Z))

In [39]:
print(Z)

[[ 0.53499653  1.26353923  1.33052542 -1.23250274  0.50992205]
 [-1.59008063  0.76502507  0.75780231 -1.34608857 -0.51769392]
 [-1.2618631   1.23078539  0.6672802   0.2248158   0.30657324]
 [ 0.5239362   0.35484036 -0.9529664   1.42430445 -0.02226357]
 [ 1.18020463 -0.27260797 -1.39528166 -1.6078228  -0.87537953]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) 

In [40]:
color = np.dtype(
                [
                    ("r", np.ubyte),
                    ("g", np.ubyte),
                    ("b", np.ubyte),
                    ("a", np.ubyte)
                ]
                )

In [41]:
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [42]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [43]:
Z= np.ones((5,3))@np.ones((3,2))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [44]:
Z = np.arange(11)
Z[(3<Z)&(Z<8)] *= -1

In [45]:
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? 

In [46]:
print(sum(range(5), -1))
# 5 + 4

9


In [47]:
print(sum(range(5), 2))
# 5 + 7

12


#### 27. Consider an integer vector Z, which of these expressions are legal?

In [48]:
Z = np.random.random((3,3))

In [49]:
Z

array([[0.1592307 , 0.06847765, 0.89791276],
       [0.01470363, 0.70406609, 0.74485257],
       [0.45666166, 0.10310149, 0.12047889]])

In [50]:
Z_to_Z = Z**Z

In [51]:
Z_to_Z

array([[0.7463425 , 0.83226403, 0.90783796],
       [0.93984121, 0.78110566, 0.80299206],
       [0.69911703, 0.79116333, 0.77494196]])

#### 28. What are the result of the following expressions?

In [52]:
np.array(0) / np.array(0)

C:\Users\Norto\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [53]:
np.array(0) // np.array(0)

C:\Users\Norto\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [54]:
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

#### 29. How to round away from zero a float array ?

In [55]:
Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

[ 2.  1.  9. -1.  4.  9. -4.  6. -5.  3.]


In [56]:
# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

[ 2.  1.  9. -1.  4.  9. -4.  6. -5.  3.]


#### 30. How to find common values between two arrays?

In [57]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[0 1 2]


#### 31. How to ignore all numpy warnings (not recommended)?

In [58]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

In [59]:
# Back to sanity
_ = np.seterr(**defaults)

In [60]:
# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0

#### 32. Is the following expressions true?

In [61]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\Norto\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? 

In [62]:
yesterday = np.datetime64('today') - np.timedelta64(1)

In [63]:
today     = np.datetime64('today')

In [64]:
tomorrow  = np.datetime64('today') + np.timedelta64(1)

In [65]:
yesterday

numpy.datetime64('2021-05-17')

In [66]:
today

numpy.datetime64('2021-05-18')

In [67]:
tomorrow

numpy.datetime64('2021-05-19')

#### 34. How to get all the dates corresponding to the month of July 2016?

In [68]:
z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')

In [69]:
print(z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? 

In [70]:
A = np.ones(3)*1
B = np.ones(3)*2

In [71]:
np.add(A,B,out=B)

array([3., 3., 3.])

In [72]:
np.divide(A,2,out=A)

array([0.5, 0.5, 0.5])

In [73]:
np.negative(A,out=A)

array([-0.5, -0.5, -0.5])

In [74]:
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods

In [75]:
Z = np.random.uniform(0,10,10)

In [76]:
print(Z - Z%1)

[1. 1. 1. 1. 9. 7. 0. 1. 9. 8.]


In [77]:
print(Z // 1)

[1. 1. 1. 1. 9. 7. 0. 1. 9. 8.]


In [78]:
print(np.floor(Z))

[1. 1. 1. 1. 9. 7. 0. 1. 9. 8.]


In [79]:
print(Z.astype(int))

[1 1 1 1 9 7 0 1 9 8]


In [80]:
print(np.trunc(Z))

[1. 1. 1. 1. 9. 7. 0. 1. 9. 8.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 

In [81]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [82]:
# without broadcasting
Z = np.tile(np.arange(0, 5), (5,1))
print(Z)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
